project:
  type: default
  output-dir: _output

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools: true
    self-contained: true
    fig-width: 10
    fig-height: 6
  pdf:
    toc: true
    toc-depth: 3
    colorlinks: true
    pdf-engine: pdflatex
    fig-width: 7
    fig-height: 5

execute:
  echo: true
  warning: false
  message: false
  cache: true

knitr:
  opts_chunk:
    fig.width: 10
    fig.height: 6
    fig.retina: 2
    connection: con
